spring:
  application:
    name: sms-be
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:spring_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: none, update, create, create-drop
    show-sql: true  # Show SQL queries in console (optional)

security:
  jwt:
    secret-key: ${JWT_SECRET:secret-key}
    expiration-time: 3600000  # Example: 1 hour in milliseconds
